estimator:
  interfaceName: ens160
  # interfaceName: eth0
  # interfaceName: usb0
uploader:
  targets:
    - network: tcp
      address: 1.2.3.4:443
    - network: tcp
      address: 5.4.3.2:443
coordinator:
  uploadSize:
    min: 1024000
    max: 102400000
  interval: 1s
  concurrent: 100
  rxTxMaxRatio: 0.09
