estimator:
  # interfaceName: ens160
  # interfaceName: eth0
  # interfaceName: usb0
  # interfaceName: enp44s0
  interfaceName: wlo1
uploader:
  targets:
    - network: tcp
      address: 1.2.3.4:443
    - network: tcp
      address: 5.6.7.8:443
coordinator:
  concurrent: 10
  # total balancer
  totalBalancerEnabled: false
  interval: 1s
  uploadSize:
    min: 1024
    max: 102400
  txRxMinRatio: 10
  txRxMaxRatio: 11
  # realtime balancer
  realtimeBalancerEnabled: true
  realtimeTxRxRatio: 10