estimator:
  # interfaceName: eth0
  interfaceName: usb0
uploader:
  targets:
    - network: tcp
      address: 1.2.3.4:443
coordinator:
  uploadSize:
    min: 1024
    max: 102400
  interval: 3s
  concurrent: 10
  rxTxMaxRatio: 0.10
